server:
  port: 8119
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  application:
    name: mapper-datasource

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.60.171.50:3306/data?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      max-lifetime: 180000
      connection-timeout: 60000
      maximum-pool-size: 12

    type: com.zaxxer.hikari.HikariDataSource

  rabbitmq:
    host: 123.60.171.50
    port: 5672
    virtual-host: /dev
    username: test_admin
    password: 123
    #消息确认方式
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          max-attempts: 4
          initial-interval: 5000

#阿⾥云OSS配置
aliyun:
  oss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tHwfZJfbPs633xJH148
    access-key-secret: 3Snf2eIasYpN6g45RL5X1FR7yf1H58
    bucketname: a39